### ISSUE TITLE
pass external db user/admin password secretly into values.yaml for synopsys-alert helm chart?

### ISSUE THREAD

**Issue by vineetmadan** [blackducksoftware/blackduck-alert#1402]
Hi All,

Planning to use an external postgresql db server (AWS RDS) for hosting sysnopsys-alert on K8s (AWS EKS). 
Going through the documentation, could not find a way to secretly pass the external db user/admin into values.yaml that could be passed to "helm install" with "-f" which would allow us to store this in source control.

 I wonder if there's a way that the chart supports?

**Comment by jamesrichard91** [comment]
Hello, you will only need to set the DB user admin password starting in Alert 6.4.0 which is going to be released soon. 
Thank you for pointing this out to us. We will need to add the ability to use secrets for the external DB Admin user.

**Comment by ChomickiM** [comment]
@vineetmadan , as an alternative to passing in the credentials into the values.yaml file you should also be able to pass in the required values through the command line when deploying helm using the --set flag in combination with environment variables. This will supersede any values set in values.yaml and you would not risk storing the values in source control.
 
For example, you can set these variables to your external databases’ credentials and use the --set flag to overwrite them when installing via helm.
`--set  postgres.adminUserName=”$DB_ADMIN_USER”  --set postgres.adminPassword=”$DB_ADMIN_PASSWORD”`
 
Would this address your concern?

**Comment by vineetmadan** [comment]
Hi @ChomickiM That's how we are using it for the time being with v6.3.1. 

I just think maintaining a values.yaml file is much easier when there are more than a few parameters which one wants to pass. In this case, there are more than just those 2 configurable parameters which we wanna pass to the chart before installing.
Having values.yaml file in source control also helps us to maintain it as source of truth when performing upgrades.

Also we would have to manage where the whole "_helm install . --set ..._ " & subsequently "_helm upgrade . --set ..._" command(s) is gonna ultimately reside (for wider usage) along with secret handling.

It's usable right now, IMHO this enhancement would probably make it a bit easier and more flexible.

**Comment by jamesrichard91** [comment]
Alert 6.5.0 will support using secrets for the database admin credentials. Thank you for the feedback @vineetmadan.
