### ISSUE TITLE
Alert does not honor port number in Black Duck URL

### ISSUE THREAD

**Issue by ki-ichino-nec** [blackducksoftware/blackduck-alert#1481]
# Issue template

## Expected behavior

Alert fully supports Black Duck port numbers other than 443.

## Actual behavior

I set Black Duck Provider URL including a port number other than 443, i.e. https://webserver:8443/.
The connectivity test was passed and Alert started to gather notifications from the Black Duck.

However, I cannot send vulnerability notifications to a Slack channel.
The following errors were reported in the Alert container when I re-sent a vulnerability notification:

```
2021-03-25 04:31:15.234  INFO 1 --- [nio-8443-exec-5] c.s.i.a.c.w.p.n.NotificationProcessor    :
Notifications to Process: 1

2021-03-25 04:31:15.342  WARN 1 --- [nio-8443-exec-5] .VulnerabilityNotificationMessageBuilder  :
Could not get the Project Version for 'https://webserver/api/projects/869fda95-d1af-44b7-a9cf-09b8b33e4a6a/versions/67fb8a00-a98c-4ee4-9ec7-f7b5abe6b6e8':
Connect to webserver:443 [webserver/10.0.1.17] failed: Connection refused (Connection refused)

2021-03-25 04:31:15.344 ERROR 1 --- [nio-8443-exec-5] c.s.i.a.p.b.c.u.AlertBlackDuckService    :
Could not retrieve the Bom component:
Connect to webserver:443 [webserver/10.0.1.17] failed: Connection refused (Connection refused)

2021-03-25 04:31:15.345 ERROR 1 --- [nio-8443-exec-5] .VulnerabilityNotificationMessageBuilder :
Could not construct the message:
Connect to webserver:443 [webserver/10.0.1.17] failed: Connection refused (Connection refused)

2021-03-25 04:31:15.347  WARN 1 --- [nio-8443-exec-5] c.s.i.a.c.audit.web.AuditEntryActions    : 
This notification could not be sent. Make sure you have a Distribution Job configured to handle this notification.


2021-03-25 04:33:12.713  WARN 1 --- [nio-8443-exec-1] .s.i.a.p.b.a.t.AddUserToProjectsRunnable :
AddUserToProjectsRunnable failed:
Connect to webserver:443 [webserver/10.0.1.17] failed: Connection refused (Connection refused)
```

It seems the Alert is trying to connect to 443 (HTTPS default) port, NOT 8443 specified in the provider configuration.

## Version

* Alert: 6.4.1
* OS: RHEL 7.9

**Comment by jamesrichard91** [comment]
Hello, using Alert 6.4.1 we are unable to reproduce the error you are seeing. We have deployed a Black Duck server at port 7777, and when we configure Alert to use that Black Duck server with the port 7777 everything is working as expected.
Are you sure you included the port number in the URL when you configured the Black Duck global configuration?

**Comment by ki-ichino-nec** [comment]
Thank you for investigation.

> Are you sure you included the port number in the URL when you configured the Black Duck global configuration?

Yes, I have configured the URL as `https://webserver:8443/` exactly.

> Are you deploying the Alert server yourself? Are you using Docker Swarm or a different deployment?

I used Docker Swarm to deploy the Alert on the same host as a Black Duck server, but a different stack from a Black Duck stack.
I basically followed the instructions in [Installing Alert in a Deployment with Black Duck](https://synopsys.atlassian.net/wiki/spaces/INTDOCS/pages/953516180/Installing+Alert+in+a+Deployment+with+Black+Duck).

I modified `hub/docker-compose.yml` so that the Alert shares the same network as the Black Duck stack.

```yaml
# appended
networks:
  default:
    external:
      name: hub_default
      # `hub` is the name of the Black Duck stack.
```

After the modification, I deployed an Alert stack.

```
docker stack deploy -c hub/docker-compose.yml -c docker-compose.local-overrides.yml alert
```

**Comment by jamesrichard91** [comment]
If you are going to be deploying Alert in a different stack than Black Duck, then you should not follow the instructions for deploying Alert with Black Duck. You should follow the instructions for [installing Alert standalone](https://synopsys.atlassian.net/wiki/spaces/INTDOCS/pages/954171432/Installing+Alert+as+a+Standalone+Installation)

**Comment by ki-ichino-nec** [comment]
I don't think that the difference of deployment methods directly relates to this issue.
I looked at Alert source codes and found that notifications from the Black Duck server would lack the port number.

Each notification includes [ProjectVersionURLs](https://github.com/blackducksoftware/blackduck-alert/blob/5fcaa233fba584fc9b35402ed04a10433c05d329/provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/builder/VulnerabilityNotificationMessageBuilder.java#L100). The URL did not have the port number which was specified in the provider URL.
The error message logged by [BlackDuckMessageBuilder](https://github.com/blackducksoftware/blackduck-alert/blob/5fcaa233fba584fc9b35402ed04a10433c05d329/provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/builder/BlackDuckMessageBuilder.java#L47) shows my observation.

```
Could not get the Project Version for 'https://webserver/api/projects/869fda95-d1af-44b7-a9cf-09b8b33e4a6a/versions/67fb8a00-a98c-4ee4-9ec7-f7b5abe6b6e8'
                                                        ^
                                                        | WITHOUT port number
```

I think that the issue is the Black Duck problem, not the Alert.

> You should follow the instructions for installing Alert standalone.

I'm going to deploy the standalone version which will not be affected by the issue.
In the network configuration, we must specify 443 port, not 8443 in the provider URL because the Alert container cannot reach the internal port 8443 of the Black Duck server (`webserver`) container in a different (isolated) stack.

Thanks.

**Comment by jamesrichard91** [comment]
If I understand what you are saying, it appears the responses from Black Duck itself include the wrong URL. The URL's included in the notifications are created by Black Duck not Alert so it is likely that your Black Duck server is incorrectly configured. It is likely there is an environment variable that you are not setting.
