### ISSUE TITLE
Build not possible, as host artifactory.internal.synopsys.com is unknown

### ISSUE THREAD

**Issue by KimSchneider** [blackducksoftware/blackduck-alert#2453]
# Issue template
## Expected behavior
* `./gradlew clean build` builds the project and `./gradlew runServer` runs the services.
## Actual behavior
* Both commands fail during `npm install` as the host `artifactory.internal.synopsys.com` can not be resolved.
## Steps to Reproduce
* Download the current release zip (v6.13.1) and unzip to folder
* Run commands
* Wait for result
## Version
**Project Version:**
* 6.13.1
**OS:**
* Windows using Ubuntu 20 in WSL

**Comment by KimSchneider** [comment]
Hi @mau-synopsys , deleting the package-lock.json leads to multiple resolve dependency warnings, conflicts and deprecation warnings. The process fails executing node-sass and results with `SyntaxError: /mnt/d/blackduck-alert-6.13.1/ui/node_modules/mime-db/db.json: Unexpected end of JSON input`. I know that broken dependency is not the projects fault, but the released version is not usable.

**Comment by mau-synopsys** [comment]
Was `./gradlew clean build` ran again? I was able to build off vpn (artifactory.internal.synopsys.com is internal network) and this was the package-lock.json generated (remove .txt portion to use as .json) if you would like to try using this package-lock.json instead.
[package-lock.json.txt](https://github.com/blackducksoftware/blackduck-alert/files/11653861/package-lock.json.txt)

**Comment by mau-synopsys** [comment]
This issue is resolved in 7.0.0 (master as of date)+ versions
