### ISSUE TITLE
getting  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by mrkchowdary** [blackducksoftware/blackduck-alert#734]
# Issue template
## Expected behavior
* Connection Successful notification will come
## Actual behavior
* ###### getting the error: Could not connect to: <our Blackduck server URL>. Could not perform the authorization request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target ###### 
## Steps to Reproduce
* After installation, I have connected the URL successfully. After clicking Test Connection under Blackduck tab, we are getting this error.
*
*
## Version
**Project Version:**

* Alert: 5.0.1
**Language Version:**

*
**OS:**

*

**Comment by psantos1113** [comment]
Thank you for your ticket.  You are having an issue with how the SSL certificates are setup.
The truststore that Alert is using for certificates does not have the certificate for Black Duck imported into the truststore.  You will need to specify the PUBLIC_HUB_WEBSERVER_HOST environment variable in order for Alert to attempt to import the certificate automatically for you.  If this does not work, then you will need to create a truststore and manually import the Black Duck certificate into it.  Once the certificate is imported into the new truststore, you need to configure Alert to use the new truststore where you just imported the certificate.
 
These are covered in our readme.md files that are included with the installation files you have downloaded to install the release.  I have provided links to updated documentation that can be found on GitHub. There are more details regarding certificates in those versions.
 
docker-compose:
https://github.com/blackducksoftware/blackduck-alert/blob/5.1.0/deployment/docker-compose/README.md
 
docker-swarm:
https://github.com/blackducksoftware/blackduck-alert/blob/5.1.0/deployment/docker-swarm/README.md

**Comment by mrkchowdary** [comment]
Thanks psantos113 for your answer. 

I have checked the above swarm README url link. 

And also I gone through my alert 5.0.1 configuration files under: 
"blackduck-alert-5.0.1-deployment/docker-swarm/hub/blackduck-alert.env" and I got the below statement
#PUBLIC_HUB_WEBSERVER_HOST is deprecated and should be replaced with the following.

I have already updated my overrides file with the following entries:
version: '3.6'
services:
  alert:
    # uncomment environment to set environment variables for the alert service.
    environment:
      - ALERT_HOSTNAME=<my blackduck server hostname only not with https>
      - ALERT_SERVER_PORT=8443
      - ALERT_LOGGING_LEVEL=DEBUG

Please provide me some inputs, might I did anything wrong in my alert configuration files?

==============================================================
From the README.md file: 


Add PUBLIC_HUB_WEBSERVER_HOST environment variable. (The value must be the hostname only.)

    Editing overrides file:

alert:
    environment:
        - PUBLIC_HUB_WEBSERVER_HOST=<BLACK_DUCK_HOST_NAME>

    Replace <BLACK_DUCK_HOST_NAME> with the hostname of the machine where Black Duck is installed.

Do not add the protocol a.k.a scheme to the value of the variable.

    Good: PUBLIC_HUB_WEBSERVER_HOST=blackduck.example.com
==============================================================

**Comment by psantos1113** [comment]
I understand the confusion.  The blackduck-alert.env file mentions that the environment variable PUBLIC_HUB_WEBSERVER_HOST is deprecated.  It is deprecated from its original use which was to define the host that Alert would be running on.  We will need to clarify that for future versions to avoid confusion.  You should not edit the blackduck-alert.env file.  The recommendation is to edit the docker-compose.local-overrides.yml file.  Please add the following environment variables to the docker-compose.local-overrides.yml file.

`
version: '3.6'
services:
  alert:
    environment:
      - ALERT_HOSTNAME=<YOUR_ALERT_HOST_NAME>
      - ALERT_SERVER_PORT=8443
      - ALERT_LOGGING_LEVEL=DEBUG
     # -- Black Duck Variables for Certificate Import
      - PUBLIC_HUB_WEBSERVER_HOST=<YOUR_BLACK_DUCK_HOST_NAME>
`

The addition of the PUBLIC_HUB_WEBSERVER_HOST environment variable will cause Alert to attempt to import the certificate into it's truststore.

If Alert and Black Duck are both running on the same host machine i.e.
`blackduck.example.com`

Then the docker-compose.local-overrides.yml file should look like this.

`
version: '3.6'
services:
  alert:
    environment:
      - ALERT_HOSTNAME=blackduck.example.com
      - ALERT_SERVER_PORT=8443
      - ALERT_LOGGING_LEVEL=DEBUG
     # -- Black Duck Variables for Certificate Import
      - PUBLIC_HUB_WEBSERVER_HOST=blackduck.example.com
`
If alert is running on a different host machine from Black Duck i.e. 
`alert.example.com`
Then the docker-compose.local-overrides.yml file should look like this:
`
version: '3.6'
services:
  alert:
    environment:
      - ALERT_HOSTNAME=alert.example.com
      - ALERT_SERVER_PORT=8443
      - ALERT_LOGGING_LEVEL=DEBUG
     # -- Black Duck Variables for Certificate Import
      - PUBLIC_HUB_WEBSERVER_HOST=blackduck.example.com
`

**Comment by mrkchowdary** [comment]
Thanks psantos1113 for your help...

I did the modification and restarted the alert service. Now that error is not re-producing in my environment.

**Comment by psantos1113** [comment]
Thank you for the update.  I will close this issue.
