### ISSUE TITLE
emails are not sending to any recipient after 5.0.1 alert installation

### ISSUE THREAD

**Issue by mrkchowdary** [blackducksoftware/blackduck-alert#736]
# Issue template
## Expected behavior
* Need to send mails from ALERT to the recipients successfully
## Actual behavior
* Not sending mails to the recipients
=============================================================
2019-11-13 18:03:09.731 ERROR 1 --- [nio-8443-exec-4] c.s.i.a.c.email.EmailMessagingService    : Could not send this email to the following recipients: [MY MAIL ID]. Reason: Couldn't connect to host, port: OUR MAIL SERVER, 25; timeout -1
=============================================================

But I am able to ping our mail server from the alert hub server:

[root@Our server hostname docker-swarm]# ping < OUR MAIL SERVER > PING OUR MAIL SERVER (OUR MAIL SERVER IP) 56(84) bytes of data.
64 bytes from OUR MAIL SERVER IP (OUR MAIL SERVER IP): icmp_seq=1 ttl=54 time=70.2 ms
64 bytes from OUR MAIL SERVER IP (OUR MAIL SERVER IP):: icmp_seq=2 ttl=54 time=69.9 ms
64 bytes from OUR MAIL SERVER IP (OUR MAIL SERVER IP):: icmp_seq=3 ttl=54 time=70.0 ms
64 bytes from OUR MAIL SERVER IP (OUR MAIL SERVER IP):: icmp_seq=4 ttl=54 time=70.2 ms
64 bytes from OUR MAIL SERVER IP (OUR MAIL SERVER IP):: icmp_seq=5 ttl=54 time=70.0 ms
64 bytes from OUR MAIL SERVER IP (OUR MAIL SERVER IP):: icmp_seq=6 ttl=54 time=70.3 ms ^C
--- OUR MAIL SERVER ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5006ms rtt min/avg/max/mdev = 69.901/70.143/70.373/0.273 ms

BTW, the alert 4.0.2 with the same SMTP mail configuration is working properly.

## Version
**Project Version:**
ALERT version 5.0.1 

**OS:**
* CentOS 7

**Comment by psantos1113** [comment]
You're using 5.0.1 now.  Was this an upgrade from 4.0.2 or a clean install on a new machine?

**Comment by mrkchowdary** [comment]
Hi psantos113, 

Let me explain my scenario here. 

Actually this is not a new installation on new machine. A couple of weeks back we installed alert 4.0.2 version using docker-swarm on same hub server in both test and prod environments. We faced some issues related to certificate and under settings section ("Daily digest hour of day" option is default 12 AM and "Purge data frequency in days". ), the values of the two sections are changing with their default value after I restarted the alert service.

Later then we upgraded our test environment with alert 5.0.0 version. After this upgrade the default values changing under settings tab got fixed. But the certification is still reproducing. I got an update that 5.0.1 version is available. So I have tried alert 5.0.1 version in my test environment, yesterday with your help the certificate issue got resolved. But new issue related to email getting in my test environment. I have used the same email options which are used in 4.0.2 & 5.0.0.

**Comment by psantos1113** [comment]
Thank you for this information.  I will investigate this further and provide an update when I have more information.

**Comment by mrkchowdary** [comment]
Sure psantos113.

**Comment by psantos1113** [comment]
Hi mrkchowdary,
You can ping the system but have you tried to telnet to the port to make sure there isn't a network issue?

Follow the instructions in this FAQ:
https://javaee.github.io/javamail/FAQ#condebug

What version of Docker Engine and Docker Swarm are you running with?
Can you also make sure that you select in Alert the SMTP EHLO checkbox in the Email Channel configuration?  
I have seen in house instances where if the EHLO checkbox isn't checked the communication between the SMTP server cannot be established.

Can you also try setting the SMTP Timeout to 0 just in case?  

You mentioned that 4.0.2  with the same SMTP configuration is working.  I assume you mean 4.2.0 because we don't have a 4.0.2 release correct?  Do you have a system running 4.2.0 with the SMTP settings that are working and 5.0.1 on another system that isn't working?

If so have you compared the email settings? Or could you provide screenshots of the settings screen?  Please remove the SMTP host and any authentication specific parameters from the screenshots if they can be provided.

**Comment by mrkchowdary** [comment]
My bad, yes your guess is correct, I have installed 4.2.0 only not 4.0.2. 
In  my test environment, I am using Docker version:  19.03.2, build 6a30dfc
It seems there is some issue with my test environment only.

BTW, I have installed ALERT 5.0.1 in my production environment and it went successful. Able to connect with any issues like certification and emails are able to send.

But i didn't ticked the SMTP EHLO checkbox in the Email Channel configuration, still I am able to send emails.

**Comment by psantos1113** [comment]
Ok it could be firewall issues on the test system.  I would compare your IPTable rules on your production versus test environments.  We have seen in our own testing differences in the IPTable rules between development test systems and QA test systems.  This can have an affect on the docker network.  Please review the IPTable rules.

**Comment by psantos1113** [comment]
Closing this issue as it appears Alert functions properly.  There is a difference between the test environment and the production environment causing issues with network traffic.

**Comment by mrkchowdary** [comment]
I will check that with our IT team. And thanks for your help.
